export const mockVideos = [
  {
    _id: "1",
    title: "Learn React in 30 Minutes",
    description: "A quick tutorial to get started with React",
    videoUrl:
      "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    thumbnailUrl: "https://picsum.photos/320/180",
    channelId: { channelName: "Code with John" },
    uploader: {
      username: "JohnDoe",
      avatar: "https://randomuser.me/api/portraits/men/1.jpg",
    },
    views: 15200,
    createdAt: "2024-01-15T10:30:00Z",
    category: "Education",
    tags: ["react", "javascript", "tutorial"],
    likes: [],
    dislikes: [],
    comments: [],
  },
  {
    _id: "2",
    title: "JavaScript Basics for Beginners",
    description: "Learn JavaScript fundamentals in this comprehensive tutorial",
    videoUrl:
      "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    thumbnailUrl: "https://picsum.photos/320/181",
    channelId: { channelName: "Tech with Jane" },
    uploader: {
      username: "JaneSmith",
      avatar: "https://randomuser.me/api/portraits/women/2.jpg",
    },
    views: 25300,
    createdAt: "2024-01-14T14:20:00Z",
    category: "Education",
    tags: ["javascript", "beginners", "tutorial"],
    likes: [],
    dislikes: [],
    comments: [],
  },
  {
    _id: "3",
    title: "Building a YouTube Clone with MERN",
    description: "Full stack tutorial on building a YouTube clone",
    videoUrl:
      "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    thumbnailUrl: "https://picsum.photos/320/182",
    channelId: { channelName: "Code with John" },
    uploader: {
      username: "JohnDoe",
      avatar: "https://randomuser.me/api/portraits/men/1.jpg",
    },
    views: 12500,
    createdAt: "2024-01-13T09:15:00Z",
    category: "Technology",
    tags: ["mern", "react", "nodejs", "mongodb"],
    likes: [],
    dislikes: [],
    comments: [],
  },
  {
    _id: "4",
    title: "Best Music Mix 2024",
    description: "Top hits of 2024",
    videoUrl:
      "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
    thumbnailUrl: "https://picsum.photos/320/185",
    channelId: { channelName: "Music Channel" },
    uploader: {
      username: "DJ Mike",
      avatar: "https://randomuser.me/api/portraits/men/3.jpg",
    },
    views: 53200,
    createdAt: "2024-01-12T20:45:00Z",
    category: "Music",
    tags: ["music", "mix", "2024"],
    likes: [],
    dislikes: [],
    comments: [],
  },
];
